"""
AI Summarization service using Ollama (local LLM).

Sends the raw transcript to Ollama and gets back structured meeting minutes
in Markdown format.

Requirements:
  - Ollama installed and running: https://ollama.ai
  - A model pulled, e.g.: ollama pull llama3
  - OLLAMA_BASE_URL and OLLAMA_MODEL set in .env (defaults: localhost:11434, llama3)
"""

import httpx
import json
from app.core.config import settings


SYSTEM_PROMPT = """You are an expert meeting minutes writer. 
Your job is to convert a raw meeting transcript into clean, structured meeting minutes in Markdown.

Always use this exact Markdown structure:

# Meeting Minutes

## Summary
A 2-3 sentence overview of what the meeting covered.

## Attendees
List any names or speakers mentioned. Write "Not identified" if none mentioned.

## Agenda Items Discussed
List the main topics discussed as bullet points.

## Key Decisions
List any decisions made during the meeting.

## Action Items
List tasks assigned, with owner and deadline if mentioned.
Format: - [ ] **[Owner]**: Task description *(Due: date if mentioned)*

## Next Steps
Brief summary of what happens after this meeting.

---
*Minutes generated by AI — please review and edit as needed.*

Rules:
- Use clean Markdown only, no HTML
- Be concise but complete  
- If information is not in the transcript, skip that section
- Do not invent names, decisions, or action items not mentioned
"""


def summarize_transcript(transcript: str) -> str:
    """
    Send transcript to Ollama and return structured minutes as Markdown.
    Raises httpx.HTTPError or RuntimeError on failure.
    """
    url = f"{settings.OLLAMA_BASE_URL}/api/chat"

    payload = {
        "model": settings.OLLAMA_MODEL,
        "stream": False,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"Please convert the following meeting transcript into structured meeting minutes:\n\n{transcript}",
            },
        ],
    }

    # Generous timeout — long transcripts can take a while locally
    try:
        with httpx.Client(timeout=300.0) as client:
            response = client.post(url, json=payload)
    except httpx.ConnectError as e:
        raise RuntimeError(
            f"Cannot connect to Ollama at {settings.OLLAMA_BASE_URL}. "
            f"Make sure Ollama is running. Error: {str(e)}"
        )
    except httpx.TimeoutException:
        raise RuntimeError(
            f"Ollama request timed out. The model {settings.OLLAMA_MODEL} may be too slow "
            f"or the transcript too long. Try a faster model (e.g., 'mistral' or 'neural-chat')."
        )

    if response.status_code != 200:
        error_detail = response.text[:500]
        raise RuntimeError(
            f"Ollama API error (HTTP {response.status_code}): {error_detail}\n"
            f"Make sure model '{settings.OLLAMA_MODEL}' is pulled. "
            f"Run: ollama pull {settings.OLLAMA_MODEL}"
        )

    try:
        data = response.json()
    except json.JSONDecodeError as e:
        raise RuntimeError(f"Failed to parse Ollama response as JSON: {str(e)}")

    # Ollama /api/chat response shape: {"message": {"role": "assistant", "content": "..."}}
    if "message" not in data:
        raise RuntimeError(f"Unexpected Ollama response format: {str(data)[:200]}")
    
    content = data.get("message", {}).get("content", "")
    if not content or not content.strip():
        raise RuntimeError(
            "Ollama returned empty response. The model may have failed to generate content. "
            "Try a different model or verify Ollama is working correctly."
        )

    return content.strip()


def check_ollama_health() -> bool:
    """Quick connectivity check — call on startup if you want early failure."""
    try:
        with httpx.Client(timeout=5.0) as client:
            r = client.get(f"{settings.OLLAMA_BASE_URL}/api/tags")
            return r.status_code == 200
    except Exception:
        return False